"""empty message

Revision ID: e9938970c086
Revises: c4b43ab4423d
Create Date: 2020-05-22 16:31:49.281398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9938970c086'
down_revision = 'c4b43ab4423d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('like', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_like_created_at'), 'like', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_like_created_at'), table_name='like')
    op.drop_column('like', 'created_at')
    # ### end Alembic commands ###
